### Upload a file
POST http://localhost:8081/api/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< C:/path/to/your/example.jpg
--WebAppBoundary--

### Open a file
GET http://localhost:8081/api/attach/open/{fileId}

### Download a file
GET http://localhost:8081/api/attach/download/{fileId}

### Delete a file
DELETE http://localhost:8081/api/attach/{fileId}

### Get all files with pagination
GET http://localhost:8081/api/attach?page=1&size=10

### Download
GET http://localhost:8081/api/v1/attach/download